spring.application.name=stock-mate

# Database Configuration (H2 File-based)
spring.datasource.url=jdbc:h2:file:~/stockmate-db;DB_CLOSE_DELAY=-1;AUTO_SERVER=true
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update

# H2 Console Configuration
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.web-allow-others=true

# Security console frames option (to allow H2 console iframe inside browser)
spring.headers.frame-options=sameorigin
